{
    "rootGroup": {
        "name": "MiNiFi Flow",
        "processors": [
            {
                "name": "Get files from /tmp/input",
                "identifier": "2f2a3b47-f5ba-49f6-82b5-bc1c86b96e27",
                "type": "org.apache.nifi.processors.standard.GetFile",
                "schedulingStrategy": "TIMER_DRIVEN",
                "schedulingPeriod": "1 sec",
                "properties": {
                    "Input Directory": "/tmp/input"
                },
                "autoTerminatedRelationships": []
            },
            {
                "name": "LogAttribute",
                "identifier": "e143601d-de4f-44ba-a6ec-d1f97d77ec94",
                "type": "org.apache.nifi.processors.standard.LogAttribute",
                "schedulingStrategy": "EVENT_DRIVEN",
                "properties": {
                },
                "autoTerminatedRelationships": [
                    "success"
                ]
            }
        ],
        "connections": [
            {
                "identifier": "098a56ba-f4bf-4323-a3f3-6f8a5e3586bf",
                "name": "GetFile/success/LogAttribute",
                "source": {
                    "id": "2f2a3b47-f5ba-49f6-82b5-bc1c86b96e27"
                },
                "destination": {
                    "id": "e143601d-de4f-44ba-a6ec-d1f97d77ec94"
                },
                "selectedRelationships": [
                    "success"
                ]
            }
        ],
        "remoteProcessGroups": [],
        "controllerServices": []
    }
}
