name: "MiNiFi-CPP CI"
on: [push, pull_request, workflow_dispatch]
jobs:
  docker_integration_tests:
    name: "Docker integration tests"
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: build
        run: mkdir build && cd build && cmake -DUSE_SHARED_LIBS= -DSTRICT_GSL_CHECKS=AUDIT -DENABLE_JNI=OFF -DDISABLE_JEMALLOC=ON -DDISABLE_SCRIPTING=ON -DENABLE_AWS=ON -DENABLE_LIBRDKAFKA=ON -DENABLE_AZURE=ON .. && make docker
      - id: install_deps
        run: |
          sudo apt update
          sudo apt install -y python3-virtualenv
      - id: test
        run: cd build && make docker-verify
