name: "MiNiFi-CPP CI"
on: [push, pull_request, workflow_dispatch]
jobs:
  macos_xcode_12_0:
    name: "macos-xcode12.0"
    runs-on: macos-10.15
    timeout-minutes: 90
    env:
      CCACHE_BASEDIR: ${{ GITHUB.WORKSPACE }}
      CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/.ccache
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: macos-xcode12.0-ccache-${{github.ref}}-${{github.sha}}
          restore-keys: |
            macos-xcode12.0-ccache-${{github.ref}}-
            macos-xcode12.0-ccache-refs/heads/main-
      - id: install_dependencies
        run: |
          brew update
          brew install ossp-uuid boost flex lua@5.3 ccache sqliteodbc automake autoconf
      - id: setup_env
        run: |
          echo "PATH=/usr/lib/ccache:/usr/local/opt/ccache/bin:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV
          echo -e "127.0.0.1\t$HOSTNAME" | sudo tee -a /etc/hosts > /dev/null
          sudo xcode-select -switch /Applications/Xcode_12.app
      - id: build
        run: |
          export PATH="/usr/local/opt/lua@5.3/lib:/usr/local/opt/lua@5.3/include:/usr/local/opt/lua@5.3/bin:$PATH"
          export PKG_CONFIG_PATH="/usr/local/opt/lua@5.3/lib/pkgconfig"
          ./bootstrap.sh -e -t && cd build  && cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_LUA_SCRIPTING=1 -DENABLE_SQL=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_RULE_MESSAGES=OFF -DSTRICT_GSL_CHECKS=AUDIT -DFAIL_ON_WARNINGS=ON .. && cmake --build . --parallel 4
